### ISSUE TITLE
Dialog 的問題

### ISSUE THREAD

**Issue by wangjenmin** [PepperClass/PepperRobotCoding#2]
請問，在使用 Choregraphe 的 Dialog 時，會遇到輸出為 <...> 的狀況，然後，當天的所有對語音的識別結果就都是 <...> 的結果，可能要到第二天才能正常。不知道是什麼狀況？

**Comment by PepperClass** [comment]
Hello~ 
用到 u(_*) $1 的功能為使用 SBR 提供之 Nuance Online STT, 次數有限(每日可用次數不太確定), 若有需要使用Online的部份, 目前建議選擇Google STT, 或Azure STT API.

**Comment by wangjenmin** [comment]
我瞭解了，謝謝您的回覆。
