### ISSUE TITLE
Dialog的output問題

### ISSUE THREAD

**Issue by wangjenmin** [PepperClass/PepperRobotCoding#3]
您好，
如果使用 Dialog box 的話，可以在 .top 的檔案裡使用 $onStopped=1 的方式處理 output 的動作。 我想請教的是，我是在 Python Script box 裡透過 ALDialog 的方式讓 pepper 對話，似乎無法使用 $onStopped=1 的方式呼叫 output ，請問有什麼方式可以處理嗎？ 
謝謝

**Comment by PepperClass** [comment]
您好:
我貼了一張圖, 新增Dialog輸出腳位
[http://servicecontrol.perobot.com.tw/photosticker/image/GithubQA/DialogQA01.png](http://servicecontrol.perobot.com.tw/photosticker/image/GithubQA/DialogQA01.png)

Dialog top內容範例如下:
u:(hi) $output1=1             #output1腳位的資料型態為"Bang"
u:(hello) $output2=你好   #output2腳位的資料型態為"String"
u:(_[男生 女生]) $output2=$1  #將使用者的說話內容取出判斷
u:(bye) 再見 $onStopped=1      #onStopped=1 通常用在結束Dialog

以上說明, 希望有解答你的問題~

**Comment by wangjenmin** [comment]
您好， 
謝謝您的回覆～～ 
Dialog box 的部份我知道，沒有問題。 

我想請教的是，「我是在 Python Script box 裡透過 ALDialog 的方式讓 pepper 對話，似乎無法使用 $onStopped=1 的方式呼叫 output ，請問有什麼方式可以處理嗎？」

再請教是否有可能處理？ 或是應該用其他方式？ 
謝謝。

**Comment by PepperClass** [comment]
您好：
請參考下圖, 看這個方法是否適用
[第二張圖](http://servicecontrol.perobot.com.tw/photosticker/image/GithubQA/DialogQA02.png)

u:(_[hello yes]) hi  ^call(ALMemory.raiseEvent("output1", $1))

以上說明, 希望有解答你的問題~

**Comment by wangjenmin** [comment]
您好，

這種方式可以，解決了！ 
非常感謝！
