### ISSUE TITLE
Can't get the API data response

### ISSUE THREAD

**Issue by celiecelie** [PepperClass/PepperRobotCoding#4]
Hi, I am new to Pepper and having issue with API call.
We are trying to call the Pepper Weather API and got stuck at this code below (from $.getJSON), where the API is being called but won't return any value to the Pepper screen tablet.

```function getData() {
		var url = "http://api.openweathermap.org/data/2.5/weather?q=tainan,TW&appid=933fb925d18d02371b6d9e2b3fd8f018&lang=zh_tw";
		$.getJSON( url, function( data ) {
			 document.getElementById("demo").innerHTML = JSON.stringify(data);
			 document.getElementById("myWether").value = data.weather[0].description;
			 document.getElementById("myDegree").value = (data.main.temp-273.15).toFixed(2);
			 session.service("ALTextToSpeech").then(function (tts) {
          		tts.say('目前天氣' + document.getElementById("myWether").value + ',氣溫'+document.getElementById("myDegree").value+'度');
        	  });
		});
```

We've been trying to installed the apps to robot and accessed it from web (Pepper web page) and it worked fine, but when we tried to run it and accessed from Pepper tablet, the button won't return anything to the screen.

**Comment by PepperClass** [comment]
Sorry to reply to you too late, I tried the sample code again and still is worked,
so I think maybe Pepper's tablet maybe did not connected to internet, you can use ALTabletService.showWebview("http://www.google.com/") to check the connection status!
